# Example PlatformIO Project Configuration Override
# ------------------------------------------------------------------------------
# Copy to platformio_override.ini to activate overrides
# ------------------------------------------------------------------------------
# Please visit documentation: https://docs.platformio.org/page/projectconf.html

[platformio]
#default_envs = matrix2go_esp32, solo2go_esp32, solo2go_esp32_oled, solo2go_esp32_eth, solo2go_esp32_dmx, solo2go_esp32_eth_dmx, solo2go_esp32_diff, duo2go_esp32, duo2go_esp32_dmx, tetra2go_esp32, tetra2go_esp32_oled, tetra2go_esp32_diff, tetra2go_esp32_eth, octa2go_esp32, octa2go_esp32_oled, octa2go_esp32_eth # put the name(s) of your own build environment here. You can define as many as you need
default_envs = octa2go_esp32_eth, solo2go_esp32_eth, solo2go_esp32_eth_dmx, tetra2go_esp32_eth

[env:matrix2go_esp32]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Matrix2Go\"
  -D SERVERNAME=\"Matrix2Go\"
  -D WLED_AP_SSID=\"WLED-Matrix2Go\"
  -D PIXEL_COUNTS="256"
  -D DATA_PINS="2"
  -D DEFAULT_LED_COUNT=256
  -D ABL_MILLIAMPS_DEFAULT=1000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_GRB"
custom_usermods = audioreactive
lib_deps = ${esp32_idf_V4.lib_deps}
  ${esp32.AR_lib_deps}
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:solo2go_esp32]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Solo2Go\"
  -D SERVERNAME=\"Solo2Go\"
  -D WLED_AP_SSID=\"WLED-Solo2Go\"
  -D PIXEL_COUNTS="100"
  -D DATA_PINS="2"
  -D DEFAULT_LED_COUNT=100
  -D ABL_MILLIAMPS_DEFAULT=5000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_RGB"
custom_usermods = audioreactive
lib_deps = ${esp32_idf_V4.lib_deps}
  ${esp32.AR_lib_deps}
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:solo2go_esp32_oled]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Solo2Go-OLED\"
  -D SERVERNAME=\"Solo2Go-OLED\"
  -D WLED_AP_SSID=\"WLED-Solo2Go-OLED\"
  -D PIXEL_COUNTS="100"
  -D DATA_PINS="2"
  -D DEFAULT_LED_COUNT=100
  -D ABL_MILLIAMPS_DEFAULT=5000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_RGB"
  -D FLD_TYPE=SSD1306_64
  -D I2CSCLPIN=22
  -D I2CSDAPIN=21
custom_usermods = usermod_v2_four_line_display_ALT
lib_deps = ${esp32_idf_V4.lib_deps}
  lennarthennigs/ESP Rotary@^2.1.2
	olikraus/U8g2@^2.36.18
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:solo2go_esp32_eth]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Solo2Go-Eth\"
  -D SERVERNAME=\"Solo2Go-Eth\"
  -D WLED_AP_SSID=\"WLED-Solo2Go-Eth\"
  -D PIXEL_COUNTS="100"
  -D WLED_USE_ETHERNET
  -D WLED_ETH_DEFAULT=WLED_ETH_ESP32DEUX
  -D WLED_DISABLE_ESPNOW
  -D DATA_PINS="2"
  -D DEFAULT_LED_COUNT=100
  -D ABL_MILLIAMPS_DEFAULT=5000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_RGB"
lib_deps = ${esp32_idf_V4.lib_deps}
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:solo2go_esp32_dmx]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Solo2Go-DMX\"
  -D SERVERNAME=\"Solo2Go-DMX\"
  -D WLED_AP_SSID=\"WLED-Solo2Go-DMX\"
  -D WLED_ENABLE_DMX
lib_deps = ${esp32_idf_V4.lib_deps}
monitor_filters = esp32_exception_decoder
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:solo2go_esp32_eth_dmx]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Solo2Go-Eth-DMX\"
  -D SERVERNAME=\"Solo2Go-Eth-DMX\"
  -D WLED_AP_SSID=\"WLED-Solo2Go-Eth-DMX\"
  -D WLED_USE_ETHERNET
  -D WLED_ETH_DEFAULT=WLED_ETH_ESP32DEUX
  -D WLED_ENABLE_DMX
lib_deps = ${esp32_idf_V4.lib_deps}
monitor_filters = esp32_exception_decoder
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:solo2go_esp32_diff]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Solo2Go-Diff\"
  -D SERVERNAME=\"Solo2Go-Diff\"
  -D WLED_AP_SSID=\"WLED-Solo2Go-Diff\"
  -D PIXEL_COUNTS="100,100,100,100,100"
  -D DATA_PINS="2,27,26,25,33"
  -D DEFAULT_LED_COUNT=500
  -D ABL_MILLIAMPS_DEFAULT=25000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_RGB"
lib_deps = ${esp32_idf_V4.lib_deps}
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio


[env:duo2go_esp32]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Duo2Go_v2\"
  -D SERVERNAME=\"Duo2Go_v2\"
  -D WLED_AP_SSID=\"WLED-Duo2Go_v2\"
  -D PIXEL_COUNTS="100,100"
  -D DATA_PINS="2,13"
  -D DEFAULT_LED_COUNT=200
  -D ABL_MILLIAMPS_DEFAULT=10000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_RGB"
lib_deps = ${esp32_idf_V4.lib_deps}
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:duo2go_esp32_dmx]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Duo2Go-DMX\"
  -D SERVERNAME=\"Duo2Go-DMX\"
  -D WLED_AP_SSID=\"WLED-Duo2Go-DMX\"
  -D WLED_ENABLE_DMX
lib_deps = ${esp32_idf_V4.lib_deps}
monitor_filters = esp32_exception_decoder
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:tetra2go_esp32]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Tetra2Go\"
  -D SERVERNAME=\"Tetra2Go\"
  -D WLED_AP_SSID=\"WLED-Tetra2Go\"
  -D PIXEL_COUNTS="100,100,100,100"
  -D DATA_PINS="2,13,12,14"
  -D DEFAULT_LED_COUNT=400
  -D ABL_MILLIAMPS_DEFAULT=20000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_RGB"
custom_usermods = audioreactive
lib_deps = ${esp32_idf_V4.lib_deps}
  ${esp32.AR_lib_deps}
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:tetra2go_esp32_oled]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Tetra2Go-OLED\"
  -D SERVERNAME=\"Tetra2Go-OLED\"
  -D WLED_AP_SSID=\"WLED-Tetra2Go-OLED\"
  -D PIXEL_COUNTS="100,100,100,100"
  -D DATA_PINS="2,13,12,14"
  -D DEFAULT_LED_COUNT=400
  -D ABL_MILLIAMPS_DEFAULT=20000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_RGB"
  -D FLD_TYPE=SSD1306_64
  -D I2CSCLPIN=22
  -D I2CSDAPIN=21
custom_usermods = usermod_v2_four_line_display_ALT
lib_deps = ${esp32_idf_V4.lib_deps}
  lennarthennigs/ESP Rotary@^2.1.2
	olikraus/U8g2@^2.36.18
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:tetra2go_esp32_diff]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Tetra2Go-Diff\"
  -D SERVERNAME=\"Tetra2Go-Diff\"
  -D WLED_AP_SSID=\"WLED-Tetra2Go-Diff\"
  -D PIXEL_COUNTS="100,100,100,100,100,100,100,100"
  -D DATA_PINS="2,13,12,14,27,26,25,33"
  -D DEFAULT_LED_COUNT=800
  -D ABL_MILLIAMPS_DEFAULT=40000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_RGB"
lib_deps = ${esp32_idf_V4.lib_deps}
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:tetra2go_esp32_eth]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Tetra2Go-Eth\"
  -D SERVERNAME=\"Tetra2Go-Eth\"
  -D WLED_AP_SSID=\"WLED-Tetra2Go-Eth\"
  -D RLYPIN=-1
  -D WLED_USE_ETHERNET
  -D WLED_ETH_DEFAULT=WLED_ETH_ESP32DEUX
  -D BTNPIN=-1
  -D WLED_DISABLE_ESPNOW
  -D PIXEL_COUNTS="100,100,100,100"
  -D DATA_PINS="2,13,12,14"
  -D DEFAULT_LED_COUNT=400
  -D ABL_MILLIAMPS_DEFAULT=20000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_RGB"
lib_deps = ${esp32_idf_V4.lib_deps}
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:octa2go_esp32]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Octa2Go\"
  -D SERVERNAME=\"Octa2Go\"
  -D WLED_AP_SSID=\"WLED-Octa2Go\"
  -D PIXEL_COUNTS="100,100,100,100,100,100,100,100"
  -D DATA_PINS="2,13,12,14,4,16,32,33"
  -D DEFAULT_LED_COUNT=800
  -D ABL_MILLIAMPS_DEFAULT=40000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_RGB"
custom_usermods = audioreactive
lib_deps = ${esp32_idf_V4.lib_deps}
  ${esp32.AR_lib_deps}
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:octa2go_esp32_eth]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Octa2Go-Eth\"
  -D SERVERNAME=\"Octa2Go-Eth\"
  -D WLED_AP_SSID=\"WLED-Octa2Go-Eth\"
  -D PIXEL_COUNTS="100,100,100,100,100,100,100,100"
  -D DATA_PINS="2,13,12,14,4,16,32,33"
  -D DEFAULT_LED_COUNT=800
  -D WLED_USE_ETHERNET
  -D WLED_ETH_DEFAULT=WLED_ETH_ESP32DEUX
  -D WLED_DISABLE_ESPNOW
  -D ABL_MILLIAMPS_DEFAULT=40000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_RGB"
lib_deps = ${esp32_idf_V4.lib_deps}
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio

[env:octa2go_esp32_oled]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_RELEASE_NAME=\"Octa2Go-OLED\"
  -D SERVERNAME=\"Octa2Go-OLED\"
  -D WLED_AP_SSID=\"WLED-Octa2Go-OLED\"
  -D PIXEL_COUNTS="100,100,100,100,100,100,100,100"
  -D DATA_PINS="2,13,12,14,4,16,32,33"
  -D DEFAULT_LED_COUNT=800
  -D WLED_USE_ETHERNET
  -D WLED_ETH_DEFAULT=WLED_ETH_ESP32DEUX
  -D WLED_DISABLE_ESPNOW
  -D ABL_MILLIAMPS_DEFAULT=40000
  -D LED_MILLIAMPS_DEFAULT=30
  -D DEFAULT_LED_COLOR_ORDER="COL_ORDER_RGB"
  -D FLD_TYPE=SSD1306_64
  -D I2CSCLPIN=22
  -D I2CSDAPIN=21
custom_usermods = usermod_v2_four_line_display_ALT
lib_deps = ${esp32_idf_V4.lib_deps}
  lennarthennigs/ESP Rotary@^2.1.2
	olikraus/U8g2@^2.36.18
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio